### ISSUE TITLE
Device count and data interval limitations

### ISSUE THREAD

**Issue by mattie-mcp** [aws-solutions/iot-device-simulator#10]
Are the limitations for device count (1,000) and data transmission interval (1000 ms) hard limits or are they configurable? Looking to use this tool for load testing and exercising different traffic patterns at scale.

**Comment by ldefauw-triumphtech** [comment]
It looks like they are hard limits in the code but you can customize it and build it to your liking. I'm actually trying that now.

**Comment by fhoueto-amz** [comment]
There is a limit for 100 devices and  data transmission interval up to 604799 sec. 
Closing the issue
