### ISSUE TITLE
Make simulator Long Live

### ISSUE THREAD

**Issue by usmanumar2010** [aws-solutions/iot-device-simulator#12]
Iot device simulator stops sending data after a while .How can I make it long Live  ?

**Comment by gsingh04** [comment]
The default simulation time is 2minutes, you can adjust this setting while creating the device type. You can also update the device type and adjust **Data Transmission Duration** to your desired value of simulation run time.

**Comment by usmanumar2010** [comment]
I want to register device which run for 5 years.Would i write 5 years in milliseconds in the Data Transmission Duration ? Can it be more flexible?

**Comment by gsingh04** [comment]
Thanks for the feature request. We have added it to the backlog items to be evaluated for future releases.

**Comment by fhoueto-amz** [comment]
Hi Usman
This enhancement did not receive enough support to be added to the roadmap, as a result, I am closing it for now. You may reopen the request in the future or create a new request linking to this one if you would like the decision reevaluated.
Rgds
Fabien
