### ISSUE TITLE
Allow edit of device types in console UI

### ISSUE THREAD

**Issue by jebbens** [aws-solutions/iot-device-simulator#18]
Once a device type is created using the console, the only way to edit the attributes is by going to the raw data in the dynamodb table. It would be nice to have the ability to edit the device in the console UI.

**Comment by maykays** [comment]
Thank you for the suggestion. I have added it to the backlog.

**Comment by G-Lenz** [comment]
We have done a complete refresh of the solution in v3.0.0. Device Types can be edited through the UI in the newest version.
