### ISSUE TITLE
Update Angular Major Version and Packages from v5 to v6

### ISSUE THREAD

**Issue by msidwell** [aws-solutions/iot-device-simulator#19]
After deploying this application, I ran into some really tough development troubles due to this repo's significantly outdated Angular codebase, I've taken some time to try out a first step towards Angular v6 and it seems to be functional thus far. Is a steady march towards v11 something that would be worthwhile for this repo?

I have a pull request sitting around that I'll attach to this issue for reference.

**Comment by msidwell** [comment]
#20

**Comment by G-Lenz** [comment]
In the latest version, v3.0.0, we have done a complete refresh of the solutions and switched the UI from Angular to React.
