### ISSUE TITLE
[Question] Counter instead of random?

### ISSUE THREAD

**Issue by byongwu** [aws-solutions/iot-device-simulator#22]
When I use this simulator, it created random values on JSON format.
It is useful. Thank you.
However, I wish to have a simple monotonic counter as well starting from 1, 2, 3, ..., on and on.
Also, I wish each device to have a unique ID and keeping that ID.
It is important because in IoT testing we want to test

* Packet loss ratio
* Packet out-of-order ratio
* Packet travel time analysis

I searched for the simple counter option but could not find. Am I missing it? Or do you think this feature is not yet available?

**Comment by tomnight** [comment]
Thanks for reaching out, the counter option is a current feature of the solution but we will add this to our backlog and review the requirement in the next release.

**Comment by fhoueto-amz** [comment]
Hi Byong-Wu,
 This enhancement did not receive enough support to be added to the roadmap, as a result, I am closing it for now. You may reopen the request in the future or create a new request linking to this one if you would like the decision reevaluated.
rgds
Fabien
