### ISSUE TITLE
[Issue] Failed to deploy. Need to improve doc

### ISSUE THREAD

**Issue by byongwu** [aws-solutions/iot-device-simulator#23]
Hi,

@georgebearden . Thanks for improving the code. After your change of https://github.com/awslabs/iot-device-simulator/blame/master/deployment/build-s3-dist.sh#L19, I see that it's not actually matching the document description of https://github.com/awslabs/iot-device-simulator/blame/master/README.md#L28.

Specifically, could you kindly explain the difference between `base source bucket name` and the new `open-source bucket name`. How should we create the new `open-source bucket name`?

Thanks,

**Comment by tomnight** [comment]
Sorry for the confusion the docs and the build script need updating, which we will correct in the next release.

For the example: ./build-s3-dist.sh solutions solutions-github trademarked-solution-name v1.0.0

**solution**
Is the prefix of the bucket the source code will be hosted in. Lambda requires the source code to be in a bucket in the same region as the lambda function. The build script uses this value plus the region for the bucket name. eg: solutiuons-us-east-1

**solutions-github**
is not actually required so you can just pass in any value as its not used by the script. 

**trademarked-solution-name**
This is the name of the sub folder in s3 where the source code is stored

**version** 
This is the sub folder under the trademark name for the version of the source code.

With the example being deployed to us-east-1 you would expect the code to be in:

s3://solution-us-east-1/trademarked-solution-name/v1.0.0

Hope this helps, and we will get this cleaned up.

**Comment by fhoueto-amz** [comment]
This issue has been fixed in v 3.0.0 -see  https://github.com/aws-solutions/iot-device-simulator/blob/main/README.md?plain=1#L64
