### ISSUE TITLE
[Question] Why does it require public S3 access?

### ISSUE THREAD

**Issue by byongwu** [aws-solutions/iot-device-simulator#24]
Why? Public S3 is prohibited in some federated accounts.
We might want to compile and run the simulator in private contained account.

**Comment by tomnight** [comment]
Could you elaborate on this? non of the S3 buckets created by the solution are public?

**Comment by G-Lenz** [comment]
We have done a complete refresh of the solution in v3.0.0. None of the S3 buckets contain public access in the updated solution.
