### ISSUE TITLE
Add Array as an attribute data type

### ISSUE THREAD

**Issue by JoaoVidal94** [aws-solutions/iot-device-simulator#25]
How can I customize the IoT Device Simulator to have an array as an attribute data type in Device Type definition?

**Comment by fhoueto-amz** [comment]
Hi @JoaoVidal94 
in v3.0.0, you can specify an array and have one value selected randomly from that array in the attribute for a device type definition
![image](https://github.com/aws-solutions/iot-device-simulator/assets/99417891/156790ab-66c2-47be-8ae7-155731092d01)
Closing this as resolved
Rgds
Fabien
