### ISSUE TITLE
Change MQTT Destination to use GreenGrass Core Device

### ISSUE THREAD

**Issue by devin-patterson** [aws-solutions/iot-device-simulator#26]
I have a use case to change the destination for MQTT messages for the simulated devices. The ideal scenario would be to make this configurable. As of now, it seems it delivers to IoT Core dynamically pulling the address. I would like to plugin this address and port, allowing for example to use GreenGrass as a destination for the device messages.

**Comment by G-Lenz** [comment]
Hi @devin-patterson currently there is no way to modify the endpoint as it is obtained in the ECS Fargate tasks, and there is no way to modify the image used for those tasks. We are currently exploring using Lambda instead of ECS, which will make it possible to change the endpoint directly in the Lambda function itself.

**Comment by devin-patterson** [comment]
George,

Thank you very much for the response. Is there any way to hard code a
different endpoint before deploying for example to use a Greengrass
destination? Appreciate any help.

Regards,

Devin

**Comment by G-Lenz** [comment]
@devin-patterson Currently the only way possible to do it would require building your own docker image. The files needed for the image are in the source/simulator folder. You would have to change the endpoint in source/simulator/index.js to point to your own endpoint. After that, you would have to build the image and host it on your own, and then change the ECS task definition to point to your new container image.

**Comment by fhoueto-amz** [comment]
Hi @devin-patterson 
This enhancement did not receive enough support to be added to the roadmap. I am closing it for now. You may reopen the request in the future or create a new request linking to the old one if you would like the decision reevaluated.
Rgds
Fabien

**Comment by fhoueto-amz** [comment]
Hi @devin-patterson
This enhancement did not receive enough support to be added to the roadmap. I am closing it for now. You may reopen the request in the future or create a new request linking to the old one if you would like the decision reevaluated.
Rgds
Fabien
